<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>MRI Quality Assurance Metrics</title>
  <meta name="description" content="MRI Quality Assurance Metrics" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="MRI Quality Assurance Metrics" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="MRI Quality Assurance Metrics" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R-stats for ENIGMA project. </a></li>

<li class="divider"></li>
<li class="chapter" data-level="0.1" data-path=""><a href="#load-libraries"><i class="fa fa-check"></i><b>0.1</b> Load libraries</a></li>
<li class="chapter" data-level="0.2" data-path=""><a href="#which-mri-qa-metric-are-we-studying-and-why"><i class="fa fa-check"></i><b>0.2</b> Which MRI QA metric are we studying and why?</a></li>
<li class="chapter" data-level="0.3" data-path=""><a href="#load-data"><i class="fa fa-check"></i><b>0.3</b> Load data</a></li>
<li class="chapter" data-level="0.4" data-path=""><a href="#inspect-data"><i class="fa fa-check"></i><b>0.4</b> Inspect Data</a></li>
<li class="chapter" data-level="0.5" data-path=""><a href="#create-new-data-frames"><i class="fa fa-check"></i><b>0.5</b> Create new data frames</a></li>
<li class="chapter" data-level="0.6" data-path=""><a href="#data-visualization"><i class="fa fa-check"></i><b>0.6</b> Data Visualization</a></li>
<li class="chapter" data-level="0.7" data-path=""><a href="#annotated-qi1-plots"><i class="fa fa-check"></i><b>0.7</b> Annotated QI1 plots</a></li>
<li class="chapter" data-level="0.8" data-path=""><a href="#linear-models"><i class="fa fa-check"></i><b>0.8</b> Linear models</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MRI Quality Assurance Metrics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">MRI Quality Assurance Metrics</h1>
</div>
<p>This purpose of this script is to explore MRI QA metrics in more detail and determine their influence on outcomes of interest.</p>
<div id="load-libraries" class="section level2 hasAnchor" number="0.1">
<h2><span class="header-section-number">0.1</span> Load libraries<a href="#load-libraries" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.2     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.4.2     ✔ tibble    3.2.1
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.1     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div>
</div>
<div id="which-mri-qa-metric-are-we-studying-and-why" class="section level2 hasAnchor" number="0.2">
<h2><span class="header-section-number">0.2</span> Which MRI QA metric are we studying and why?<a href="#which-mri-qa-metric-are-we-studying-and-why" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We are focusing on Mortamet’s first quality index, or QI1, which measures the number of artifactual intensities in the air surrounding the head and above the nasio-cerebellar axis. Smaller QI1 values reflect better scan quality. We chose to study QI1 because we observed that the majority of participants have QI1 values of zero. Furthermore those that have non-zero QI1 values have QI1 values that are relatively greater than zero (i.e., not negligible).</p>
</div>
<div id="load-data" class="section level2 hasAnchor" number="0.3">
<h2><span class="header-section-number">0.3</span> Load data<a href="#load-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Work with the brainage_final.csv which has the cleaned Q1_1 data for all participants appended in the “qi_1” column.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load brainage_final.csv which contains 12 columns (participant ID + 11 variables of interest): sex, ASD diagnoses, PSS dx, total dx, total dx group, age band, scan age, ENIGMA age prediction, ENIGMA BAG, BrainChart centile score, qi_1</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>brainage_final <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;/KIMEL/tigrlab/scratch/csun/brainage_proj/data/processed/brainage_final.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 287 Columns: 12
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (6): participant, sex, ASD_dx, dx, total_dx_group, age_band
## dbl (6): total_dx, Age, age_prediction, BAG, centile, qi_1
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># brainage_final</span></span></code></pre></div>
</div>
<div id="inspect-data" class="section level2 hasAnchor" number="0.4">
<h2><span class="header-section-number">0.4</span> Inspect Data<a href="#inspect-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Resource: <a href="http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics#summary-function" class="uri">http://www.sthda.com/english/wiki/descriptive-statistics-and-graphics#summary-function</a></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine summary statistics for qi_1</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brainage_final<span class="sc">$</span>qi_1)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA&#39;s 
## 0.000000 0.000000 0.000000 0.000024 0.000000 0.004482        1</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the IQR </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>IQR <span class="ot">&lt;-</span> <span class="fu">IQR</span>(brainage_final<span class="sc">$</span>qi_1, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># set na.rm = TRUE to remove NA&#39;s</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the IQR method does not really tell us much in our case because both the Q1 and Q3 are equal to zero</span></span></code></pre></div>
<p>Based on these results, the range is 0 to 0.004482, mean is 0.000024, and median is 0. There is one participant (433) who is missing qi_1 value (shows up as NA). According to TAY QC dashboard, participant 433 has completed T1 scan.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># first filter out any NA values in qi_1 </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>brainage_filtered <span class="ot">&lt;-</span> brainage_final <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(qi_1))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># identify potential extreme values</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(brainage_filtered<span class="sc">$</span>qi_1)</span></code></pre></div>
<p><img src="06_mri_qa_effects_files/figure-html/Identify%20potential%20qi_1%20outliers-1.png" width="672" /></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(brainage_filtered<span class="sc">$</span>qi_1)</span></code></pre></div>
<p><img src="06_mri_qa_effects_files/figure-html/Identify%20potential%20qi_1%20outliers-2.png" width="672" /></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(brainage_filtered<span class="sc">$</span>qi_1)</span></code></pre></div>
<p><img src="06_mri_qa_effects_files/figure-html/Identify%20potential%20qi_1%20outliers-3.png" width="672" />
Plots do not really show much because most values are zero.</p>
</div>
<div id="create-new-data-frames" class="section level2 hasAnchor" number="0.5">
<h2><span class="header-section-number">0.5</span> Create new data frames<a href="#create-new-data-frames" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset brainage_final to create a new data frame that only includes participants with QI1 values of zero</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>zero_qi1 <span class="ot">&lt;-</span> brainage_final <span class="sc">%&gt;%</span> <span class="fu">filter</span>(qi_1 <span class="sc">==</span> <span class="dv">0</span>) </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>zero_qi1</span></code></pre></div>
<pre><code>## # A tibble: 251 × 12
##    participant     sex    ASD_dx dx      total_dx total_dx_group age_band   Age
##    &lt;chr&gt;           &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;    &lt;dbl&gt;
##  1 sub-CMH00000001 Female No     Non-PSS        5 4+             11-14     13.8
##  2 sub-CMH00000003 Female Yes    PSS            5 4+             15-17     15.3
##  3 sub-CMH00000004 Male   Yes    Non-PSS        2 2-3            15-17     15.1
##  4 sub-CMH00000005 Male   Yes    Non-PSS        1 0-1            11-14     12.4
##  5 sub-CMH00000007 Female Yes    Non-PSS        2 2-3            15-17     16.2
##  6 sub-CMH00000008 Female Yes    Non-PSS        5 4+             15-17     17.1
##  7 sub-CMH00000009 Female Yes    PSS            3 2-3            11-14     13.6
##  8 sub-CMH00000013 Female No     PSS            2 2-3            15-17     15.7
##  9 sub-CMH00000016 Male   No     PSS            5 4+             15-17     15.8
## 10 sub-CMH00000017 Female &lt;NA&gt;   Non-PSS        4 4+             18-21     20.0
## # ℹ 241 more rows
## # ℹ 4 more variables: age_prediction &lt;dbl&gt;, BAG &lt;dbl&gt;, centile &lt;dbl&gt;,
## #   qi_1 &lt;dbl&gt;</code></pre>
<p>zero_qi1 is a data frame with 251 participants who have qi_1 of 0</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset brainage_final to create a new data frame that only includes participants with non-zero QI_1 values</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>nonzero_qi1 <span class="ot">&lt;-</span> brainage_final <span class="sc">%&gt;%</span> <span class="fu">filter</span>(qi_1 <span class="sc">!=</span> <span class="dv">0</span>) </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>nonzero_qi1</span></code></pre></div>
<pre><code>## # A tibble: 35 × 12
##    participant     sex    ASD_dx dx      total_dx total_dx_group age_band   Age
##    &lt;chr&gt;           &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;    &lt;dbl&gt;
##  1 sub-CMH00000024 Male   &lt;NA&gt;   PSS            4 4+             21+       24.8
##  2 sub-CMH00000027 Female No     PSS            1 0-1            15-17     17.0
##  3 sub-CMH00000028 Female &lt;NA&gt;   PSS            5 4+             18-21     19.6
##  4 sub-CMH00000046 Female &lt;NA&gt;   PSS            6 4+             21+       23.5
##  5 sub-CMH00000050 Male   Yes    PSS            3 2-3            11-14     14.4
##  6 sub-CMH00000062 Female Yes    PSS            2 2-3            11-14     11.2
##  7 sub-CMH00000086 Female &lt;NA&gt;   PSS            7 4+             21+       23.6
##  8 sub-CMH00000107 Female Yes    PSS            1 0-1            11-14     14.3
##  9 sub-CMH00000108 Male   &lt;NA&gt;   PSS            4 4+             21+       23.0
## 10 sub-CMH00000118 Female No     Non-PSS        3 2-3            15-17     15.9
## # ℹ 25 more rows
## # ℹ 4 more variables: age_prediction &lt;dbl&gt;, BAG &lt;dbl&gt;, centile &lt;dbl&gt;,
## #   qi_1 &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset brainage_final to create a new data frame that only includes participants with extreme QI1 values (qi_1 ≥ 0.5E-04)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>extreme_qi1 <span class="ot">&lt;-</span> brainage_final <span class="sc">%&gt;%</span> <span class="fu">filter</span>(qi_1 <span class="sc">&gt;=</span> <span class="fl">0.5E-04</span>) </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>extreme_qi1</span></code></pre></div>
<pre><code>## # A tibble: 12 × 12
##    participant     sex    ASD_dx dx      total_dx total_dx_group age_band   Age
##    &lt;chr&gt;           &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;    &lt;dbl&gt;
##  1 sub-CMH00000028 Female &lt;NA&gt;   PSS            5 4+             18-21     19.6
##  2 sub-CMH00000046 Female &lt;NA&gt;   PSS            6 4+             21+       23.5
##  3 sub-CMH00000050 Male   Yes    PSS            3 2-3            11-14     14.4
##  4 sub-CMH00000086 Female &lt;NA&gt;   PSS            7 4+             21+       23.6
##  5 sub-CMH00000176 Male   &lt;NA&gt;   PSS            5 4+             21+       24.8
##  6 sub-CMH00000252 Female &lt;NA&gt;   PSS            6 4+             21+       24.9
##  7 sub-CMH00000281 Female No     PSS            1 0-1            11-14     14.4
##  8 sub-CMH00000283 Male   &lt;NA&gt;   Non-PSS        2 2-3            18-21     19.4
##  9 sub-CMH00000319 Female &lt;NA&gt;   Non-PSS        4 4+             21+       23.4
## 10 sub-CMH00000394 Male   No     Non-PSS        3 2-3            11-14     12.0
## 11 sub-CMH00000420 Female No     PSS            8 4+             15-17     17.8
## 12 sub-CMH00000426 Female No     Non-PSS        3 2-3            11-14     13.7
## # ℹ 4 more variables: age_prediction &lt;dbl&gt;, BAG &lt;dbl&gt;, centile &lt;dbl&gt;,
## #   qi_1 &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># subset brainage_final to create a new data frame that only includes participants without extreme QI1 values (qi_1 &lt; 0.5E-04)</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>mild_qi1 <span class="ot">&lt;-</span> brainage_final <span class="sc">%&gt;%</span> <span class="fu">filter</span>(qi_1 <span class="sc">&lt;</span> <span class="fl">0.5E-04</span>)  </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>mild_qi1</span></code></pre></div>
<pre><code>## # A tibble: 274 × 12
##    participant     sex    ASD_dx dx      total_dx total_dx_group age_band   Age
##    &lt;chr&gt;           &lt;chr&gt;  &lt;chr&gt;  &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;    &lt;dbl&gt;
##  1 sub-CMH00000001 Female No     Non-PSS        5 4+             11-14     13.8
##  2 sub-CMH00000003 Female Yes    PSS            5 4+             15-17     15.3
##  3 sub-CMH00000004 Male   Yes    Non-PSS        2 2-3            15-17     15.1
##  4 sub-CMH00000005 Male   Yes    Non-PSS        1 0-1            11-14     12.4
##  5 sub-CMH00000007 Female Yes    Non-PSS        2 2-3            15-17     16.2
##  6 sub-CMH00000008 Female Yes    Non-PSS        5 4+             15-17     17.1
##  7 sub-CMH00000009 Female Yes    PSS            3 2-3            11-14     13.6
##  8 sub-CMH00000013 Female No     PSS            2 2-3            15-17     15.7
##  9 sub-CMH00000016 Male   No     PSS            5 4+             15-17     15.8
## 10 sub-CMH00000017 Female &lt;NA&gt;   Non-PSS        4 4+             18-21     20.0
## # ℹ 264 more rows
## # ℹ 4 more variables: age_prediction &lt;dbl&gt;, BAG &lt;dbl&gt;, centile &lt;dbl&gt;,
## #   qi_1 &lt;dbl&gt;</code></pre>
<p>mild_qi1 is a data frame with 274 participants who have qi_1 less than 0.5E-04 (0.0005)</p>
</div>
<div id="data-visualization" class="section level2 hasAnchor" number="0.6">
<h2><span class="header-section-number">0.6</span> Data Visualization<a href="#data-visualization" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The following code chunks in the Data Visualization section are modified versions of the code chunks in 0.7 Data Visualization of 05_merged_stats.Rmd</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative colours for sex</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>colour_f <span class="ot">&lt;-</span> <span class="st">&quot;#CC79A7&quot;</span> <span class="co"># pink</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>colour_m <span class="ot">&lt;-</span> <span class="st">&quot;#56B4E9&quot;</span> <span class="co"># light blue</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># set colours for PSS and Non-PSS </span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>colour_pss <span class="ot">&lt;-</span> <span class="st">&quot;#702A8C&quot;</span> <span class="co"># purple </span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>colour_non_pss <span class="ot">&lt;-</span> <span class="st">&quot;#FFC154&quot;</span> <span class="co"># orange</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="co"># set colours for ASD </span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>colour_ASD <span class="ot">&lt;-</span> <span class="st">&quot;#6B3E2E&quot;</span> <span class="co"># brown</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># set colours for participants with non-zero </span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>colour_qi_1 <span class="ot">&lt;-</span> <span class="st">&quot;#D55E00&quot;</span> <span class="co"># red for QI1 values &gt; 0</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>colour_qi_extreme <span class="ot">&lt;-</span> <span class="st">&quot;#AF4154&quot;</span> <span class="co"># maroon for QI1 values &gt; 0.05e-04</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a><span class="co"># or use this alternative &quot;old brick&quot; colour: #96281B </span></span></code></pre></div>
<p>Plots annotated for QI1 &gt; 0</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check for missing values</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(brainage_final))</span></code></pre></div>
<pre><code>##    participant            sex         ASD_dx             dx       total_dx 
##              0              0            142              0              0 
## total_dx_group       age_band            Age age_prediction            BAG 
##              0              0              0              0              0 
##        centile           qi_1 
##              0              1</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine range of BAG</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(brainage_final<span class="sc">$</span>BAG) </span></code></pre></div>
<pre><code>## [1] -19.3648  31.5396</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The range for BAG is -19.36 to +31.54 (round to -20 and +32)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># There are NA values for the following variables: ASD_dx [142], qi_1 [1]</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># use IQR method to identify outliers and set-up the range for Q1 and Q3</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># summary statistics for BAG to determine Q1 and Q3</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(brainage_final<span class="sc">$</span>BAG)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -19.365  -3.962   1.325   1.255   6.526  31.540</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Q1 = -3.962</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Q3 = 6.526</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>range_IQR <span class="ot">&lt;-</span> <span class="fu">IQR</span>(brainage_final<span class="sc">$</span>BAG) <span class="sc">*</span> <span class="fl">1.5</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># IQR = 10.48784</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># IQR * 1.5 = 15.73176</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>q1_IQR <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">3.962</span> <span class="sc">-</span> range_IQR</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>q3_IQR <span class="ot">&lt;-</span> <span class="fl">6.526</span> <span class="sc">+</span> range_IQR</span></code></pre></div>
</div>
<div id="annotated-qi1-plots" class="section level2 hasAnchor" number="0.7">
<h2><span class="header-section-number">0.7</span> Annotated QI1 plots<a href="#annotated-qi1-plots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Plot BAG vs centile grouped by PSS and Non-PSS ####</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot w/ annotations for participants with non-zero qi_1 values with a larger circle around</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>plot1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> brainage_final, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> dx, <span class="at">colour =</span> dx)) <span class="sc">+</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set different shapes for PSS and Non-PSS</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> dx)) <span class="sc">+</span> <span class="co"># assign colour by PSS grouping</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">data =</span> nonzero_qi1, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="co"># overlay larger red hollow circles around nonzero qi_1 values </span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>,<span class="fl">1.15</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;Non-zero QI_1&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">shape =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;white&quot;</span>))) <span class="do">### START HERE </span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>plot1</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Visualizing%20participants%20with%20QI1%20equal%20to%20zero-1.png" width="672" /></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternate plot: overlay with non-zero qi_1 values FILLED IN w/ colour_qi_1</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>plot2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> brainage_final, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> dx, <span class="at">colour =</span> dx)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> dx)) <span class="sc">+</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> nonzero_qi1, <span class="at">colour =</span> colour_qi_extreme) <span class="sc">+</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># annotate the nonzero qi_1 values by overlaying with a maroon colour</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>,<span class="fl">1.15</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;Non-zero QI_1&quot;</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>plot2</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Visualizing%20participants%20with%20QI1%20equal%20to%20zero-2.png" width="672" /></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># do not add labs(colour = &quot;Diagnostic Group&quot;) because PSS is not actually a diagnoses, </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Based on the plots, there does not seem to be a clear trend because both PSS and Non-PSS participants have non-zero qi_1 values </span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="do">#### Plot BAG vs centile grouped by sex and age_band panels ####</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot w/ annotations for participants with non-zero qi_1 values with a larger circle around</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>plot_sex <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> brainage_final, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> sex, <span class="at">colour =</span> sex)) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set different shapes for PSS and Non-PSS</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> sex)) <span class="sc">+</span> <span class="co"># assign colour by PSS grouping</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">data =</span> nonzero_qi1, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span> <span class="co"># overlay larger black hollow circles around nonzero qi_1 values </span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.25</span>,<span class="fl">1.25</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Female&quot;</span> <span class="ot">=</span> colour_f, <span class="st">&quot;Male&quot;</span> <span class="ot">=</span> colour_m)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;Sex Assigned at Birth&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>plot_sex</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Visualizing%20participants%20with%20QI1%20equal%20to%20zero-3.png" width="672" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Plot BAG vs centile grouped by dx w/ sex panels ####</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> brainage_final, <span class="fu">aes</span>(<span class="at">x =</span> age_band, <span class="at">y =</span> centile, <span class="at">colour =</span> dx, <span class="at">shape =</span> dx))<span class="sc">+</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">position=</span><span class="fu">position_dodge</span>(<span class="at">width=</span><span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">position=</span><span class="fu">position_jitterdodge</span>(<span class="at">dodge.width=</span><span class="fl">0.9</span>)) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> nonzero_qi1, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add geom_point() to overlay the points</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>sex) <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>)</span></code></pre></div>
<p><img src="06_mri_qa_effects_files/figure-html/Visualizing%20participants%20with%20QI1%20equal%20to%20zero-4.png" width="672" /></p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;centile_BAG_qi1_outline.png&quot;</span>, <span class="at">plot =</span> plot1, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">dpi =</span> <span class="dv">800</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;centile_BAG_qi1_filled.png&quot;</span>, <span class="at">plot =</span> plot2, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">dpi =</span> <span class="dv">800</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">&quot;centile_BAG_qi1_sex.png&quot;</span>, <span class="at">plot =</span> plot_sex, <span class="at">height =</span> <span class="dv">5</span>, <span class="at">width =</span> <span class="dv">7</span>, <span class="at">dpi =</span> <span class="dv">800</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p>Plots annotated for extreme QI1 values</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot w/ annotations for participants with non-zero qi_1 values with a larger circle around</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>plot3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> brainage_final, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> dx, <span class="at">colour =</span> dx)) <span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set different shapes for PSS and Non-PSS</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> dx)) <span class="sc">+</span> <span class="co"># assign colour by PSS grouping</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">data =</span> extreme_qi1, <span class="at">colour =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="co"># overlay larger black hollow circles around nonzero qi_1 values </span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>,<span class="fl">1.15</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a>plot3</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Visualizing%20participants%20with%20QI1%20%3C%200.5E-06-1.png" width="672" /></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternate plot: overlay with non-zero qi_1 values FILLED IN w/ colour_qi_1</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>plot4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> brainage_final, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> dx, <span class="at">colour =</span> dx)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> dx)) <span class="sc">+</span> </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> extreme_qi1, <span class="at">colour =</span> colour_qi_extreme) <span class="sc">+</span> </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># annotate the nonzero qi_1 values by overlaying with a maroon colour</span></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>,<span class="fl">1.15</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;Non-zero QI_1&quot;</span>)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>plot4</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Visualizing%20participants%20with%20QI1%20%3C%200.5E-06-2.png" width="672" />
## Plots excluding extreme QI1
Plotting the effect of excluding participants with QI1 &gt; 0</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot w/ annotations for participants with non-zero qi_1 values with a larger circle around</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> zero_qi1, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> dx, <span class="at">colour =</span> dx)) <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set different shapes for PSS and Non-PSS</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> dx)) <span class="sc">+</span> <span class="co"># assign colour by PSS grouping</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>,<span class="fl">1.15</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Centile%20vs%20BAG%20grouped%20by%20dx%20excl%20nonzero%20qi_1-1.png" width="672" /></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot w/ annotations for participants with qi_1 values ≥ 0.5E-04</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mild_qi1, <span class="fu">aes</span>(<span class="at">x =</span> BAG, <span class="at">y =</span> centile, <span class="at">shape =</span> dx, <span class="at">colour =</span> dx)) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set different shapes for PSS and Non-PSS</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> dx)) <span class="sc">+</span> <span class="co"># assign colour by PSS grouping</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span>lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add linear regression line that includes 95% confidence region by default</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a> <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.15</span>,<span class="fl">1.15</span>), <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># use scale_y_continuous to set the range of the y-axis, expand to add some padding to ensure no values are cut-off</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>age_band) <span class="sc">+</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;PSS&quot;</span> <span class="ot">=</span> colour_pss, <span class="st">&quot;Non-PSS&quot;</span> <span class="ot">=</span> colour_non_pss)) <span class="sc">+</span> <span class="co"># set colours for PSS grouping</span></span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">xlab</span>(<span class="st">&quot;ENIGMA Derived Brain Age Gap&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;BrainChart Centile Score&quot;</span>) <span class="sc">+</span> </span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;&quot;</span>, <span class="at">shape =</span> <span class="st">&quot;&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="06_mri_qa_effects_files/figure-html/Centile%20vs%20BAG%20grouped%20by%20dx%20excl%20extreme%20qi_1-1.png" width="672" /></p>
</div>
<div id="linear-models" class="section level2 hasAnchor" number="0.8">
<h2><span class="header-section-number">0.8</span> Linear models<a href="#linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Are the participants with non-zero qi_1 values driving the correlation between centile scores and brain age gap?</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># apply linear model to mild_qi1</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>lm_centile <span class="ot">&lt;-</span> <span class="fu">lm</span>(centile <span class="sc">~</span> sex <span class="sc">*</span> dx <span class="sc">*</span> age_band, <span class="at">data =</span> mild_qi1)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(lm_centile) <span class="co"># perform ANOVA on the linear model</span></span></code></pre></div>
<pre><code>## Call:
##    aov(formula = lm_centile)
## 
## Terms:
##                       sex        dx  age_band    sex:dx sex:age_band
## Sum of Squares   0.196936  0.568109  0.359812  0.007125     0.209571
## Deg. of Freedom         1         1         3         1            3
##                 dx:age_band sex:dx:age_band Residuals
## Sum of Squares     0.018057        0.044436 21.064332
## Deg. of Freedom           3               3       258
## 
## Residual standard error: 0.2857354
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">aov</span>(lm_centile)) <span class="co"># verify assumptions (normal distribution, homoscedasticity, additivity)</span></span></code></pre></div>
<p><img src="06_mri_qa_effects_files/figure-html/ANOVA%20linear%20models%20for%20centile%20scores-1.png" width="672" /><img src="06_mri_qa_effects_files/figure-html/ANOVA%20linear%20models%20for%20centile%20scores-2.png" width="672" /><img src="06_mri_qa_effects_files/figure-html/ANOVA%20linear%20models%20for%20centile%20scores-3.png" width="672" /><img src="06_mri_qa_effects_files/figure-html/ANOVA%20linear%20models%20for%20centile%20scores-4.png" width="672" /></p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(lm_centile)) <span class="co"># identify strength of interactions</span></span></code></pre></div>
<pre><code>##                  Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## sex               1  0.197  0.1969   2.412 0.12163   
## dx                1  0.568  0.5681   6.958 0.00885 **
## age_band          3  0.360  0.1199   1.469 0.22341   
## sex:dx            1  0.007  0.0071   0.087 0.76792   
## sex:age_band      3  0.210  0.0699   0.856 0.46470   
## dx:age_band       3  0.018  0.0060   0.074 0.97405   
## sex:dx:age_band   3  0.044  0.0148   0.181 0.90896   
## Residuals       258 21.064  0.0816                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># age</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>lm_centile_age <span class="ot">&lt;-</span> <span class="fu">lm</span>(centile <span class="sc">~</span> sex <span class="sc">*</span> dx <span class="sc">*</span> Age, <span class="at">data =</span> mild_qi1)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(lm_centile_age)</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = lm_centile_age)
## 
## Terms:
##                       sex        dx       Age    sex:dx   sex:Age    dx:Age
## Sum of Squares   0.196936  0.568109  0.411873  0.006581  0.011608  0.039414
## Deg. of Freedom         1         1         1         1         1         1
##                 sex:dx:Age Residuals
## Sum of Squares    0.000297 21.233560
## Deg. of Freedom          1       266
## 
## Residual standard error: 0.2825339
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(lm_centile_age))</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value Pr(&gt;F)   
## sex           1  0.197  0.1969   2.467 0.1174   
## dx            1  0.568  0.5681   7.117 0.0081 **
## Age           1  0.412  0.4119   5.160 0.0239 * 
## sex:dx        1  0.007  0.0066   0.082 0.7742   
## sex:Age       1  0.012  0.0116   0.145 0.7033   
## dx:Age        1  0.039  0.0394   0.494 0.4829   
## sex:dx:Age    1  0.000  0.0003   0.004 0.9514   
## Residuals   266 21.234  0.0798                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dx: p = 0.0081 # this is LESS significant than the lm fitted that includes qi_1 values &gt; 0.5E-04 (p = 0.00449)</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Age: p = 0.0239 # same as above</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># in general it seems like removing the extreme qi_1 values dampens the correlation?</span></span></code></pre></div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># apply linear model to mild_qi1 </span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="do">## age bands</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>lm_BAG <span class="ot">&lt;-</span> <span class="fu">lm</span>(BAG <span class="sc">~</span> sex <span class="sc">*</span> dx <span class="sc">*</span> age_band, <span class="at">data =</span> mild_qi1)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># figure out how to do the analysis by category - e.g., linear model for just the youngest age group or lm for the participants with 5+ total disorders</span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(lm_BAG)</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = lm_BAG)
## 
## Terms:
##                       sex        dx  age_band    sex:dx sex:age_band
## Sum of Squares    702.339   152.244   341.839     3.148      129.426
## Deg. of Freedom         1         1         3         1            3
##                 dx:age_band sex:dx:age_band Residuals
## Sum of Squares       81.425          76.426 13709.038
## Deg. of Freedom           3               3       258
## 
## Residual standard error: 7.289431
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(lm_BAG))</span></code></pre></div>
<pre><code>##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## sex               1    702   702.3  13.218 0.000335 ***
## dx                1    152   152.2   2.865 0.091722 .  
## age_band          3    342   113.9   2.144 0.095071 .  
## sex:dx            1      3     3.1   0.059 0.807878    
## sex:age_band      3    129    43.1   0.812 0.488254    
## dx:age_band       3     81    27.1   0.511 0.675176    
## sex:dx:age_band   3     76    25.5   0.479 0.696861    
## Residuals       258  13709    53.1                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sex: p = 0.000335 # less significant compared to when extreme qi_1 values are included (p= 0.000111) but the overall effect is negligible?</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="co"># dx: p = 0.091722</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># age_band: p = 0.095071 # this is interesting b/c effect on age_band on BAG became MORE significant when extreme qi_1 were removed</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="do">## scan age</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>lm_age <span class="ot">&lt;-</span> <span class="fu">lm</span>(BAG <span class="sc">~</span> sex <span class="sc">*</span> dx <span class="sc">*</span> Age, <span class="at">data =</span> brainage_final)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="co"># figure out how to do the analysis by category - e.g., linear model for just the youngest age group or lm for the participants with 5+ total disorders</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(lm_age)</span></code></pre></div>
<pre><code>## Call:
##    aov(formula = lm_age)
## 
## Terms:
##                       sex        dx       Age    sex:dx   sex:Age    dx:Age
## Sum of Squares    802.941   161.546   119.584     6.554    35.362    10.056
## Deg. of Freedom         1         1         1         1         1         1
##                 sex:dx:Age Residuals
## Sum of Squares      26.919 14541.602
## Deg. of Freedom          1       279
## 
## Residual standard error: 7.219449
## Estimated effects may be unbalanced</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(lm_age))</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## sex           1    803   802.9  15.405 0.000109 ***
## dx            1    162   161.5   3.099 0.079413 .  
## Age           1    120   119.6   2.294 0.130974    
## sex:dx        1      7     6.6   0.126 0.723148    
## sex:Age       1     35    35.4   0.678 0.410820    
## dx:Age        1     10    10.1   0.193 0.660829    
## sex:dx:Age    1     27    26.9   0.516 0.472954    
## Residuals   279  14542    52.1                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(mild_qi1<span class="sc">$</span>centile, mild_qi1<span class="sc">$</span>BAG, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  mild_qi1$centile and mild_qi1$BAG
## t = -13.905, df = 272, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.7089434 -0.5696048
## sample estimates:
##        cor 
## -0.6445957</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># r = -0.6445957 (compared to -0.634 when including qi_1 &gt; 0.5E-04)</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall the extreme qi_1 values do not really affect the correlation</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(zero_qi1<span class="sc">$</span>centile, zero_qi1<span class="sc">$</span>BAG, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  zero_qi1$centile and zero_qi1$BAG
## t = -13.095, df = 249, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.7065454 -0.5589715
## sample estimates:
##        cor 
## -0.6385928</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># r = -0.6385928</span></span></code></pre></div>
<ul>
<li>Are the participants with non-zero qi_1 values driving the older brain age observed in males?</li>
</ul>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/sunclara/ENIGMA_data/Rmd_rendered/%s",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "section"
},
"toolbar": {
"position": "fixed"
},
"share": {
"github": true
}
});
});
</script>

</body>

</html>
